-- Première série de fiches d'aide (rédigée le 01/10/2026, modifiable dans l'onglet Processus).
insert into public.fiches_aide (titre, onglets, profils, tags, declencheur, etapes, points_attention, liens, periodicite, date_echeance) values

($t$Importer un relevé bancaire$t$,
 array['/comptabilite','/comptabilite/import'],
 array['tresorier','president','administrateur'],
 array['relevé','banque','import','export Excel','xlsx','doublon','solde'],
 $t$À réception des opérations bancaires, au moins une fois par mois (idéalement chaque semaine en période de rentrée).$t$,
 $j$["Télécharger depuis la banque en ligne l'export Excel (.xlsx) des opérations — pas le relevé PDF.",
     "Si des dons figurent dans le relevé, ouvrir le coffre avant l'import (bouton « Déverrouiller ») : les fiches donateurs seront créées d'office.",
     "Comptabilité → « Importer relevé » → choisir le fichier.",
     "Contrôler le solde : l'écart entre le solde de la banque (ligne « Solde au ») et celui de Préau doit être nul ou expliqué.",
     "Passer les lignes en revue : « déjà en compta » (grisées, décochées) et « doublon possible ±5 j » (surlignées) — comparer avec l'opération affichée en pointillés avant de cocher.",
     "Vérifier la catégorie proposée de chaque ligne et la corriger si besoin.",
     "Scolarité : vérifier la famille proposée dans la colonne Rattachement ; si un versement mêle mensualités, mois d'avance et frais de dossier, le ventiler avec le chevron.",
     "Cliquer « Importer N opération(s) » (bouton en bas à droite).",
     "Traiter ensuite les lignes en ambre (filtre « À vérifier ») dans la Comptabilité."]$j$::jsonb,
 $t$Les versements de juillet et d'août relèvent de l'année scolaire suivante ; ceux de juin, de l'année en cours. Les virements de l'Amitié Sainte-Anne doivent être répartis entre les familles (fiche dédiée). La date « À jour au » affichée en tête des pages suit le dernier relevé intégré.$t$,
 $j$[{"libelle":"Importer un relevé","href":"/comptabilite/import"},{"libelle":"Comptabilité","href":"/comptabilite"}]$j$::jsonb,
 'mensuelle', null),

($t$Rattacher un paiement de scolarité à une famille$t$,
 array['/comptabilite','/scolarite'],
 array['tresorier','president','administrateur','secretaire'],
 array['scolarité','mensualité','famille','rattacher','affectation','frais de dossier','mois d''avance'],
 $t$Une écriture de scolarité porte la pastille ambre « ⚠ À compléter » dans la Comptabilité.$t$,
 $j$["Comptabilité → activer « Mode modification » → cliquer la ligne.",
     "Dans le cadre « Famille », choisir la famille et l'année scolaire ; la nature (mensualité, mois d'avance, frais de dossier) suit la catégorie de l'écriture.",
     "Rattacher la totalité du montant : la pastille passe au vert « Scolarité » quand l'onglet Frais de scolarité est entièrement alimenté.",
     "Si l'écriture couvre plusieurs familles ou plusieurs natures : fermer la fenêtre, déplier la ligne (chevron) et la ventiler en sous-écritures, puis rattacher chacune.",
     "Contrôler dans Frais de scolarité que le réglé de la famille a bien évolué (année suivie en source « Comptabilité »)."]$j$::jsonb,
 $t$Juillet–août → année scolaire suivante ; juin → année en cours. Familles homonymes : nom suivi de l'initiale du père (Picard A, Picard H) ; l'initiale n'est qu'un indice, vérifier le libellé bancaire. « Frais d'inscription » = frais de dossier.$t$,
 $j$[{"libelle":"Comptabilité","href":"/comptabilite"},{"libelle":"Frais de scolarité","href":"/scolarite"}]$j$::jsonb,
 'mensuelle', null),

($t$Répartir un virement de l'Amitié Sainte-Anne$t$,
 array['/comptabilite','/scolarite'],
 array['tresorier','president','administrateur'],
 array['ASA','Amitié Sainte-Anne','Amitie','virement groupé','répartir','familles aidées','aide'],
 $t$Une ligne porte l'alerte ambre « Virement groupé Amitié Sainte-Anne : à répartir entre les familles aidées ».$t$,
 $j$["Obtenir de l'Amitié Sainte-Anne le détail du virement : familles aidées, montant et période pour chacune.",
     "Comptabilité → « Mode modification » → déplier la ligne (chevron).",
     "Ventiler en une sous-écriture par famille, catégorie « Frais de scolarité » (mensualités).",
     "Rattacher chaque sous-écriture à sa famille et à l'année scolaire concernée.",
     "L'alerte disparaît d'elle-même lorsque la totalité du montant est répartie."]$j$::jsonb,
 $t$L'Amitié Sainte-Anne reverse des dons qu'elle collecte pour aider des familles : ce sont des frais de scolarité, pas des dons à l'ARIL (aucun reçu fiscal). Une « avance subvention » versée en été couvre l'année scolaire suivante.$t$,
 $j$[{"libelle":"Comptabilité","href":"/comptabilite"}]$j$::jsonb,
 'ponctuelle', null),

($t$Mois d'avance : versement, suivi et départ d'un enfant$t$,
 array['/scolarite','/comptabilite'],
 array['tresorier','president','administrateur','secretaire','directrice'],
 array['mois d''avance','dépôt','départ','CM2','restitution','consommé'],
 $t$Arrivée d'un nouvel enfant (été précédant l'entrée) ou départ d'un enfant.$t$,
 $j$["Arrivée : le mois d'avance est versé une fois par enfant, l'été précédant son entrée, au tarif mensuel de la famille.",
     "En Comptabilité, classer le versement en « Mois d'avance (dépôts) » et le rattacher à la famille (nature mois d'avance).",
     "Fin de CM2 : le mois d'avance éponge le dernier mois (juin) de l'enfant — renseigner « Dépôt consommé cette année » sur l'inscription de la famille.",
     "Départ avant le CM2 : décider avec la famille de la restitution (dépense rattachée « mois d'avance ») ou d'un don.",
     "Surveiller la pastille violette ↩ (enfant parti, dépôt non rendu) et la tuile « Mois d'avance en banque »."]$j$::jsonb,
 $t$Le mois d'avance n'est jamais compté dans le réglé des frais de scolarité. La tuile « Mois d'avance en banque » indique la somme à conserver de côté pour le compte des familles.$t$,
 $j$[{"libelle":"Frais de scolarité","href":"/scolarite"}]$j$::jsonb,
 'annuelle', null),

($t$Inscrire une nouvelle famille$t$,
 array['/scolarite','/scolarite/eleves'],
 array['tresorier','president','administrateur','secretaire','directrice'],
 array['inscription','nouvelle famille','barème','tarif','frais de dossier','élèves','espace familles'],
 $t$Une famille confirme l'inscription d'un ou plusieurs enfants.$t$,
 $j$["Frais de scolarité → choisir l'année → « + Ajouter une famille ».",
     "Indiquer le nombre d'enfants : le montant mensuel se remplit d'après le barème de l'année.",
     "Encaisser les frais de dossier (60 € par enfant entrant) et le mois d'avance, puis les rattacher à la famille depuis la Comptabilité.",
     "Frais de scolarité → « Élèves » : enregistrer chaque enfant (prénom, classe d'entrée).",
     "Ouvrir l'accès à l'Espace familles : invitation par courriel, puis bouton « Rattacher »."]$j$::jsonb,
 null,
 $j$[{"libelle":"Frais de scolarité","href":"/scolarite"},{"libelle":"Élèves","href":"/scolarite/eleves"}]$j$::jsonb,
 'ponctuelle', null),

($t$Enregistrer un don et établir le reçu fiscal$t$,
 array['/dons','/recus-fiscaux','/comptabilite'],
 array['tresorier','president','administrateur','resp-mecenat'],
 array['don','reçu fiscal','CERFA','donateur','coffre','RE_'],
 $t$Un don est reçu (virement, chèque, espèces, HelloAsso).$t$,
 $j$["Ouvrir le coffre (bouton « Déverrouiller ») : les coordonnées des donateurs sont chiffrées.",
     "Virement : le don est créé d'office à l'import du relevé — compléter la fiche du donateur (nom, adresse, code postal et ville, courriel).",
     "Chèque ou espèces : saisir la date de réception du don (antérieure ou égale à la date d'encaissement).",
     "Vérifier la catégorie du donateur : particulier ou personne morale (raison sociale).",
     "Reçus fiscaux → établir le reçu : numéro attribué automatiquement ; un reçu par don, ou un reçu annuel par donateur.",
     "Envoyer le reçu puis indiquer son état « envoyé »."]$j$::jsonb,
 $t$Particulier : article 200 du CGI ; entreprise : article 238 bis. Un reçu établi est figé. Si le donateur ne souhaite pas de reçu, choisir l'état « Pas de reçu demandé ».$t$,
 $j$[{"libelle":"Dons","href":"/dons"},{"libelle":"Reçus fiscaux","href":"/recus-fiscaux"}]$j$::jsonb,
 'ponctuelle', null),

($t$Ouvrir et refermer le coffre des données donateurs$t$,
 array['/dons','/mecenat/pipeline','/recus-fiscaux','/parametres'],
 array['tresorier','president','administrateur','resp-mecenat'],
 array['coffre','chiffrement','phrase secrète','code de secours','verrouillé','déverrouiller'],
 $t$Une page affiche « 🔒 » à la place des noms des donateurs.$t$,
 $j$["Cliquer « Déverrouiller » et saisir la phrase secrète (ou le code de secours).",
     "La clé reste dans la mémoire du navigateur jusqu'à la fermeture de l'onglet ou au verrouillage.",
     "Sur un poste partagé, verrouiller le coffre en fin de séance (Paramètres → Sécurité des données donateurs)."]$j$::jsonb,
 $t$Ne jamais écrire la phrase secrète ni le code de secours dans Préau, ni les transmettre par courriel. Phrase perdue : seul le code de secours permet de rouvrir le coffre.$t$,
 $j$[{"libelle":"Paramètres","href":"/parametres"}]$j$::jsonb,
 'ponctuelle', null),

($t$Clôturer un exercice comptable$t$,
 array['/comptabilite','/comptabilite/bilan','/budget','/parametres'],
 array['tresorier','president','administrateur'],
 array['clôture','exercice','bilan','31 août','solde','budget'],
 $t$Fin de l'exercice, au 31 août.$t$,
 $j$["Importer tous les relevés bancaires jusqu'au 31 août.",
     "Lever toutes les alertes « À vérifier » et « Dons à régulariser » de l'exercice.",
     "Rapprocher le solde de Préau du solde bancaire au 31 août ; expliquer tout écart.",
     "Rapprocher le total des dons de la Comptabilité de celui de l'onglet Dons.",
     "Comptabilité → Bilan → période « année » → exporter en PDF pour le conseil d'administration.",
     "Paramètres → créer l'exercice suivant et le rendre actif ; préparer son budget prévisionnel."]$j$::jsonb,
 null,
 $j$[{"libelle":"Bilan","href":"/comptabilite/bilan"},{"libelle":"Paramètres","href":"/parametres"}]$j$::jsonb,
 'annuelle', '2027-08-31'),

($t$Déposer la déclaration 2070-SD auprès des impôts$t$,
 array['/comptabilite','/ca'],
 array['tresorier','president','administrateur'],
 array['DGFiP','impôts','2070','déclaration','SIE','revenus patrimoniaux','échéance'],
 $t$Chaque année, avant l'échéance de début mai.$t$,
 $j$["Recenser les revenus patrimoniaux de l'année civile précédente (intérêts, rentes…).",
     "Remplir le formulaire 2070-SD.",
     "Le déposer auprès du service des impôts des entreprises (SIE) avant l'échéance.",
     "Conserver l'accusé de dépôt et le signaler au conseil d'administration."]$j$::jsonb,
 $t$L'absence de dépôt entraîne une mise en demeure et une amende (150 € en 2026 pour la déclaration 2025). La déclaration porte sur l'année civile, pas sur l'exercice scolaire.$t$,
 '[]'::jsonb,
 'annuelle', '2027-05-05'),

($t$Préparer un conseil d'administration$t$,
 array['/ca','/comptabilite/bilan'],
 array['president','tresorier','secretaire','administrateur','directrice','directeur-spirituel'],
 array['CA','conseil','bilan','ordre du jour','AG','compte rendu'],
 $t$Trois semaines avant la date du conseil.$t$,
 $j$["Fixer la date et l'ordre du jour ; le diffuser aux membres.",
     "Éditer le bilan de la période (Comptabilité → Bilan → Export PDF).",
     "Préparer les points financiers : trésorerie, budget consommé, frais de scolarité perçus face au dû, collecte de dons.",
     "Lister les décisions à soumettre au vote.",
     "Après le conseil : rédiger et diffuser le compte rendu."]$j$::jsonb,
 null,
 $j$[{"libelle":"Conseil d'administration","href":"/ca"},{"libelle":"Bilan","href":"/comptabilite/bilan"}]$j$::jsonb,
 'trimestrielle', null),

($t$Passation au prochain trésorier$t$,
 array['/processus','/parametres'],
 array['tresorier','president'],
 array['passation','trésorier','accès','documentation','succession'],
 $t$Changement de trésorier.$t$,
 $j$["Transmettre le compte de rôle « Trésorier » et en faire changer le mot de passe.",
     "Transmettre la phrase secrète et le code de secours du coffre, de vive voix ou sur papier.",
     "Transmettre les accès bancaires et les comptes techniques de l'application (base de données, hébergement, dépôt du code).",
     "Parcourir ensemble les fiches d'aide périodiques (relevés, clôture, 2070, reçus fiscaux).",
     "Faire le point sur l'onglet « En cours » et les alertes en suspens.",
     "Mettre à jour le nom et la signature du trésorier : Paramètres → Association (modèle de reçu)."]$j$::jsonb,
 null,
 $j$[{"libelle":"Paramètres","href":"/parametres"}]$j$::jsonb,
 'ponctuelle', null),

($t$Régler les frais de scolarité et obtenir une attestation$t$,
 array['/espace','/espace/paiements'],
 array['famille'],
 array['paiement','virement','attestation','mensualité','retard','mois d''avance'],
 $t$Chaque mois, ou pour obtenir une attestation de paiement.$t$,
 $j$["Effectuer le virement de la mensualité avant la fin du mois, en indiquant le nom de famille dans le libellé.",
     "Consulter l'onglet « Paiements » : chaque versement reçu y apparaît après intégration du relevé bancaire par le trésorier (date « À jour au » en haut de page).",
     "Pour une attestation : cliquer « PDF » sur la ligne du paiement concerné.",
     "En cas de difficulté de paiement, prendre contact avec l'école sans attendre."]$j$::jsonb,
 $t$Un paiement très récent peut ne pas encore apparaître. Le mois d'avance, versé à l'entrée de chaque enfant, n'est pas une mensualité : il couvre le dernier mois de sa scolarité.$t$,
 $j$[{"libelle":"Mes paiements","href":"/espace/paiements"}]$j$::jsonb,
 'mensuelle', null);
